modLoader="javafml"
loaderVersion="[4,)"
license="GNU Lesser General Public License version 2.1 (LGPLv2.1)"

[[mods]]
modId="lowhight_level_machine"
version="0.0.1"
displayName="Low-Hight Level Machine"
displayURL="https://github.com/Mihail-Kuth"
logoFile="logo.png"
credits="MCreator"
authors="MCreator"
description="Simple industrial mod, provides development opportunities in EFFICIENCY or SPEED machines while maintaining the vanilla look of minecraft"

# Start of user code block mod configuration
# End of user code block mod configuration

[[mixins]]
    config = "lowhight_level_machine.mixins.json"

# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.lowhight_level_machine]]
    modId="neoforge"
    type="required"
    versionRange="[21.8.31,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.lowhight_level_machine]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.8]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.lowhight_level_machine]]
    modId="jei"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration